cloud:
  aws:
    credentials:
      access-key: AKIAT7XIBPZB52ONWOU4
      secret-key: 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
    region:
      static: us-west-1
    stack:
      auto: false

application:
  bucket:
    name: studentsources

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

